name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Install WASM target
      run: rustup target add wasm32-wasip1

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "., examples/plugins/*"

    - name: Build hyper-mcp
      run: cargo build

    - name: Build example plugins
      run: |
        for plugin in qr-code hash myip fetch fs hackernews; do
          echo "Building plugin: $plugin"
          cargo build --release --target wasm32-wasip1 --manifest-path "examples/plugins/$plugin/Cargo.toml"
        done

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Check formatting
      run: cargo fmt -- --check 